name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  id-token: write
  contents: read


  # When building PRs, always cancel the in-progress
# When building Main, don't cancel the in-progress
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}


jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@master
      - run: npm install
      - run: |
          npx open-next build --node-externals aws-sdk,sharp,better-sqlite3
          file .open-next/server-functions/default/node_modules/better-sqlite3/build/Release/better_sqlite3.node


#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: ${{ secrets.AWS_REGION }}
#          role-to-assume: ${{ secrets.AWS_ROLE }}
#
#      - run: cd aws && npm install
#      - run: npm run cdk deploy
#        if: github.event_name != 'pull_request'
#        working-directory: ./aws
#        env:
#          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
#
#      - run: npm run cdk synth -- --quiet
#        if: github.event_name == 'pull_request'
#        working-directory: ./aws
#        env:
#          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
