name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

  # When building PRs, always cancel the in-progress
# When building Main, don't cancel the in-progress
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@master
      - run: npm install
      - run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_ACCOUNT }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - run: npm run cdk deploy
        if: github.event_name != 'pull_request'
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}

      - run: npm run cdk synth
        if: github.event_name == 'pull_request'
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
